"use client";
import { useRef, useState } from "react";
import type { FamilyTree, Person } from "../../lib/types";

function generations(tree: FamilyTree) { const depth = new Map(tree.people.map((person) => [person.id, 0])); for (let pass = 0; pass < tree.people.length; pass += 1) for (const link of tree.relationships.filter((item) => item.type === "parent")) depth.set(link.toPersonId, Math.max(depth.get(link.toPersonId) ?? 0, (depth.get(link.fromPersonId) ?? 0) + 1)); const groups = new Map<number, Person[]>(); tree.people.forEach((person) => { const level = depth.get(person.id) ?? 0; groups.set(level, [...(groups.get(level) ?? []), person]); }); return { depth, groups }; }

export function FamilyTreeCanvas({ tree, onSelect }: { tree: FamilyTree; onSelect: (person: Person) => void }) {
  const { depth, groups } = generations(tree); const [view, setView] = useState({ x: 0, y: 0, scale: 1 }); const gesture = useRef<{ x: number; y: number; view: typeof view } | null>(null);
  const point = (person: Person) => { const group = groups.get(depth.get(person.id) ?? 0) ?? []; const index = group.findIndex((item) => item.id === person.id); return { x: 50 + (index - (group.length - 1) / 2) * 18, y: 28 + (depth.get(person.id) ?? 0) * 28 }; };
  const parentGroups = [...new Set(tree.relationships.filter((link) => link.type === "parent").map((link) => link.toPersonId))].map((childId) => ({ child: tree.people.find((person) => person.id === childId), parents: tree.relationships.filter((link) => link.type === "parent" && link.toPersonId === childId).map((link) => tree.people.find((person) => person.id === link.fromPersonId)).filter(Boolean) as Person[] })).filter((group) => group.child && group.parents.length);
  const begin = (event: React.PointerEvent<HTMLDivElement>) => { if ((event.target as HTMLElement).closest("button")) return; event.currentTarget.setPointerCapture(event.pointerId); gesture.current = { x: event.clientX, y: event.clientY, view }; };
  const move = (event: React.PointerEvent<HTMLDivElement>) => { if (!gesture.current) return; setView({ ...view, x: gesture.current.view.x + event.clientX - gesture.current.x, y: gesture.current.view.y + event.clientY - gesture.current.y }); };
  const end = () => { gesture.current = null; }; const zoom = (event: React.WheelEvent<HTMLDivElement>) => { event.preventDefault(); setView({ ...view, scale: Math.max(.5, Math.min(3, view.scale * (event.deltaY > 0 ? .92 : 1.08))) }); };
  return <div className="family-canvas" onPointerDown={begin} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onWheel={zoom}><div className="tree-viewport" style={{ transform: `translate(${view.x}px, ${view.y}px) scale(${view.scale})` }}><svg className="tree-connectors" viewBox="0 0 100 100" preserveAspectRatio="none">{tree.relationships.filter((link) => link.type === "spouse").map((link) => { const from = tree.people.find((person) => person.id === link.fromPersonId); const to = tree.people.find((person) => person.id === link.toPersonId); if (!from || !to) return null; const a = point(from); const b = point(to); return <line className="spouse-connector" key={link.id} x1={a.x} y1={a.y} x2={b.x} y2={b.y} />; })}{parentGroups.map(({ child, parents }) => { if (!child) return null; const childPoint = point(child); const parentPoints = parents.map(point); const left = Math.min(...parentPoints.map((item) => item.x)); const right = Math.max(...parentPoints.map((item) => item.x)); const junctionY = childPoint.y - 14; return <g className="parent-connector" key={child.id}><line x1={left} y1={parentPoints[0].y} x2={right} y2={parentPoints[0].y} /><line x1={(left + right) / 2} y1={parentPoints[0].y} x2={(left + right) / 2} y2={junctionY} /><line x1={left} y1={junctionY} x2={right} y2={junctionY} /><line x1={childPoint.x} y1={junctionY} x2={childPoint.x} y2={childPoint.y} /></g>; })}</svg>{tree.people.map((person) => { const p = point(person); return <button className="tree-card" style={{ left: `${p.x}%`, top: `${p.y}%` }} key={person.id} onClick={() => onSelect(person)}><strong>{person.displayName}</strong><span>{person.birthDate?.slice(0, 4) ?? "Year unknown"}</span></button>; })}</div></div>;
}
