INSERT INTO stories (id, title, body, original_body, date, place, created_at) VALUES ('63f9b8cc-c8e5-4c25-9a56-83315622f7e4', 'The dedication', 'It is a great honour to bring you the Darabi family tree. This is the first attempt and may probably contain errors. Please inform us of any potentially missing or inaccurate information. We hope that this family tree will be useful and updated by our future generations.

Many thanks to Mrs Nahid Jaberian, Helen Jaberian, Farnoush Darabi, Niloufar Forouzan, Mahin Darabi, Sheida Eftekhari Rad, and Mr Massoud Darabiha and Farzad Hosseinzadeh.

Nasser Darabiha and Mohammad Darabi — 21 March 2013

(The archive prints this dedication in English, Persian, French and transliterated Persian. The Persian is kept below.)', 'باعث افتخار است که شجره نامه ی خاندان دارابی و بستگان را تقدیم حضورتان نمائیم . این مجموعه برای اولین بار گرد آوری شده و محتمل است که اشتباهاتی در آن رخ داده باشد. مقتضی است چنانچه اطلاعاتی مستند برای کامل تر شدن این مجموعه دارید ما را یاری فرمائید. امید است بدین وسیله این شجره نامه برای همیشه سرافراز و جاودان بماند و نسل های آینده مان روند تکمیلی ان را ادامه داده و نسل به نسل انتقال دهند', '2013', NULL, '2026-08-27T08:32:46.753Z');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('63f9b8cc-c8e5-4c25-9a56-83315622f7e4', '85f4b8fd-8b87-454b-bfb2-4da7cdbf7727');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('63f9b8cc-c8e5-4c25-9a56-83315622f7e4', '5a818474-50c3-4487-8839-59e1bc58fb1e');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('63f9b8cc-c8e5-4c25-9a56-83315622f7e4', '3084c6e8-5081-421b-9156-993213ac28f9');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('63f9b8cc-c8e5-4c25-9a56-83315622f7e4', '1577dd18-9d83-4485-9d3d-5d3a60537fec');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('63f9b8cc-c8e5-4c25-9a56-83315622f7e4', '90173fd7-6e42-4062-bc29-ca7a0c441c16');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('63f9b8cc-c8e5-4c25-9a56-83315622f7e4', 'd41b0052-45ac-4def-adcb-a82bce02ab43');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('63f9b8cc-c8e5-4c25-9a56-83315622f7e4', '047f74e6-6bfb-4724-8674-325bc83a2934');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('63f9b8cc-c8e5-4c25-9a56-83315622f7e4', '6e2bf761-e41d-4296-a803-d92a9fd12118');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('63f9b8cc-c8e5-4c25-9a56-83315622f7e4', '9182b5b0-7052-421f-b320-9f6187125fcb');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('63f9b8cc-c8e5-4c25-9a56-83315622f7e4', 'd9bdba40-9012-433d-b1cb-34a8cfd058ee');
INSERT INTO stories (id, title, body, original_body, date, place, created_at) VALUES ('e1047326-98b5-491b-9232-f9ddb17dd68a', 'How this biography was written', 'Greetings. With thanks to Professor Nasser Darabiha, who has worked with me on putting this family tree together with great interest and perseverance and has shown me the way in a great deal of it; and to the rest of the dear family — Mrs Nahid Jaberian, Mrs Helen Jaberian, Mrs Mahin Darabi, Mr Massoud Darabiha, Mr Farzad Hosseinzadeh, Mrs Sheida Eftekhari Rad and Miss Niloufar Forouzan — who have all worked with the two of us, Mohammad and Nasser, and who will help us in the future as well. So that you may know something of the lives, the circumstances and the households of the family''s forebears, I set down a short account of each below.

Bear in mind that this material is entirely as narrated by Mr Ramazan Darabi (fifth generation), and that my own part has been only to fix the dates, to determine the ages, and to tell the material and write it down. I hope that the coming generation, reading this and seeing the family tree, will come to know their forebears, and will keep their bond and their connection with all the living members of the family.

I ask all the dear family, and the respected Jaberian family in particular, that if they know anything of Mrs Fatemeh Darabi, wife of Mr Haj Ramazan Jaberian, or of any of the principal branches, they should write it in the proper place under their own name.

Mohammad Darabi, Generation 6c5 — 21 March 2013', 'با عرض سلام ، با تشكر از آقاى پروفسور ناصر دارابيها كه با علاقه و پشتكار فراوان با اينجانب براي تشكيل شجره نامه همكارى وارائه طريق بسيار زياد داشته وهمچنين ساير فاميل عزيز مانند خانم ناهيد جابريان ، خانم هلن جابريان،خانم مهين دارابى، آقاى مسعود دارابيها، آقاى فرزاد حسين زاده، خانم شيدا افتخارى راد و دوشيزه نيلوفر فروزان كه همگى در اين راه با ما ( محمد وناصر ) همكارى نموده ودر آينده هم ما را يارى خواهند داد ،جهت آشنائى از وضعييت زندگى،اجتمائى و خانوادگى پيشينييان فاميل براى هر كدام مختصرى بشرح زير باطلاع ميرسانم
با عنايت باينكه اين مطالب كلا بروايت ازآقاى رمضان دارابى( نسل ٥) بوده ونقش اينجانب فقط تعين تاريخ ، مشخص نمودن سن ها، روايت مطالب ونگارش انها ميباشد. اميد است كه نسل آينده با خواندن اين مطالب و ديدن شجره نامه با نياكان خود آشنا شده وهمبستگى وارتباط خود را با كل اعضاء زنده فاميل حفظ نمايند. ضمنا از تمام فاميل عزيز بويژه خانواده محترم جابريان تقاضا دارم درصورتيكه مطلبى از خانم فاطمه دارابى همسر آقاى حاج رمضان جابريان يا هر يك از سر شاخه ها مى دانند با نام خود در محل مربوطه بنويسند
Mohammad Darabi, Generation 6c5 - March 21, 2013', '2013', NULL, '2026-08-27T08:32:46.753Z');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('e1047326-98b5-491b-9232-f9ddb17dd68a', '5a818474-50c3-4487-8839-59e1bc58fb1e');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('e1047326-98b5-491b-9232-f9ddb17dd68a', '85f4b8fd-8b87-454b-bfb2-4da7cdbf7727');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('e1047326-98b5-491b-9232-f9ddb17dd68a', 'd8b95bb0-e98f-44a5-a038-3f68237f5a0e');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('e1047326-98b5-491b-9232-f9ddb17dd68a', '660e6499-1a6e-4214-b532-33a428c79742');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('e1047326-98b5-491b-9232-f9ddb17dd68a', 'bfcf4349-ec32-4617-96a7-4fddfab35b38');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('e1047326-98b5-491b-9232-f9ddb17dd68a', '3084c6e8-5081-421b-9156-993213ac28f9');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('e1047326-98b5-491b-9232-f9ddb17dd68a', '1577dd18-9d83-4485-9d3d-5d3a60537fec');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('e1047326-98b5-491b-9232-f9ddb17dd68a', '047f74e6-6bfb-4724-8674-325bc83a2934');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('e1047326-98b5-491b-9232-f9ddb17dd68a', '9182b5b0-7052-421f-b320-9f6187125fcb');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('e1047326-98b5-491b-9232-f9ddb17dd68a', 'd9bdba40-9012-433d-b1cb-34a8cfd058ee');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('e1047326-98b5-491b-9232-f9ddb17dd68a', '6e2bf761-e41d-4296-a803-d92a9fd12118');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('e1047326-98b5-491b-9232-f9ddb17dd68a', 'd41b0052-45ac-4def-adcb-a82bce02ab43');
INSERT INTO stories (id, title, body, original_body, date, place, created_at) VALUES ('66c47a4c-ae2a-413a-9b65-94960fc9b131', 'Haj Chorok, first generation', 'Told by Mohammad Darabi, sixth generation.

Haj Chorok, who stands at the head of the family, was born around the years 1090 to 1100 Solar Hijri (1711–1721) in the city of Darab in Fars province. As a child he moved with his family to Shiraz. Through his ability and his great intelligence he became, while still young, a large and prominent merchant, and he started a family in Shiraz.

His business gradually prospered and he turned his mind to trade between cities. Trade was very hard in those days, for the roads were unsafe and there was none of today''s commercial and electronic communication; only real intelligence and a kind of genius made it possible. He managed it. He employed about a hundred men — clerks, secretaries, guards and riders — bought a great many mules and camels, and ran the whole thing properly: he would assemble the merchandise, load it onto the mules and camels, and with a party of riders and guards carry it towards Tabriz, which was the seat of the crown prince and the commercial centre of the country. On the way he stopped for a few days only in the most important cities — Isfahan, Rey and Qazvin — selling there what was wanted and buying what was needed for Tabriz. His last stop was Tabriz itself, where the whole consignment was sold; for the return he bought in the same way what Shiraz needed, and went back. The journey out and back took about nine months.

On one of these journeys, on a bitterly cold winter night, he came into Qazvin and reached the great caravanserai where he always put up. The gate was shut. He knocked several times, but the keeper would not open: sheltering under his korsi from the hard cold, he was too idle to get up. Haj Chorok, seeing his men perishing of cold, shouted several times and beat hard on the gate, and still the keeper never opened. He was furious, and went to another caravanserai and stayed there.

The next day he told his deputy to move the caravan on towards Tabriz and see to what was needed, and said that he would join them for Shiraz when they came back through Qazvin. He went to the bazaar and told the property brokers to buy that caravanserai for him, even if the owner had no wish to sell. In the end he managed to buy it. Then he went to the caravanserai and dismissed the keeper. The man begged forgiveness several times, but he never consented to forgive him. He stayed some months in Qazvin until his caravan returned from Tabriz, and in those months hired a manager, a keeper and staff for the place, and named it Saray-e Haj Chorok — traces of which remain in Qazvin to this day.

Haj Chorok''s caravanserai was in use as a caravanserai until 1304 (1925). In that year the property was confiscated, probably by order of Reza Shah, and given over to a large number of Sunni Roma who had been exiled to Qazvin from where they lived. After the Islamic Revolution the property was levelled, and the municipality now uses it as a car park.

Haj Chorok chose a girl from Qazvin and married her, and made a house and a life for her. From then on he stayed mostly in Qazvin, living with his new wife between the going and coming of his caravan. A son was born to them whom they named Haj Agha, and our line comes down from him.', '١- حاج چورُك نسل اول
نقل از آقاى محمد دارابی نسل ششم
آقاى حاج چورك كه راس هرم فاميل بشمار ميرود تقريبا در سالهاى ١٠٩٠ تا١١٠٠ هجرى شمسى درشهر داراب استان فارس متولد ميگردد .دركودكى همراه خانواده اش به شهر شيراز كوچ مينمايد، باتوجه به توانايى و هوش زيادش توانسته در جوانى به بازرگانى بزرگ وبرجسته تبديل گردد و در شهر شيراز تشكيل خانواده ميدهد، كم كم كارش رونق گرفته وبفكر تجارت در بين شهر ها مى افتد ، در ان زمان كار تجارت بدليل عدم امنيت راهها و عدم وجودارتباطات تجارى والكترونيكى كنونى بسيار مشكل بود وفقط با هوش زياد ونبوق بسيار امكان پذير بود، ايشان هم موفق گرديد با استخدام حدود ١٠٠نفر كارمند ، منشى، نگهبان وسوار كار وخريد قاطر وشترهاى زيادى وهمچنين اعمال مديريت درست از عهده اين كار برايد ، بطوريكه مالاتجاره را تهيه مى كرد وپس از بار زدن به قاطر وشترها بهمراه گروهى سواركار ومحافظ ، بارها رابه قصد شهر تبريز كه وليعهد نشين ومركز تجارت بود حمل مينمود ودر بين راه فقط در شهرهاى بسيار مهم مانند اصفهان ، رى وقزوين توقف چند روزه داشت . در اين شهرها كالاهاى مورد نياز رافروخته وكالاهاى لازم براى تبريز راخريدارى ميكرد ودرنهايت اخرين توقف او شهر تبريزبود كه كل كالاها در آنجا بفروش ميرسيد وبراى برگشت خود نيز بهمان شكل خريد كالاهاى مورد نياز شيراز را تهيه و به شيراز باز مى گشت ، اين رفت وبرگشت حدود نه ماه طول مى كشيد
.
در يكى از سفرهاى خود در زمستانى بسيار سرد هنگام شب وارد قزوين مى گردد وطبق معمول به كاروانسرايى بزرگ كه هميشه در آنجا اطراق مى كرد مى رسد، درب كاروانسرا بسته بود او چندين بار در زد ولى سرايدار در را باز نكرد، سرايدار كه از سرماى بسيار شديد در زير كرسى پناه گرفته بود از تنبلى حاضر به باز كردن در كاروانسرا نگرديد ،حاج چورك كه مى ديد كاركنانش از سرما از بين مى روند چندين بار فرياد زده ومحكم در را به صدادرآورد ولى سرايدار هرگز در را باز نكرد. او بسيار عصبانى شد وبه كاروانسراى ديگر رفت ودر آنجا اقامت كرد. روز بعد به معاون خود گفت كه قافله را بطرف تبريز حركت داده وكارهاى لازم را انجام دهد ودر برگشت به قزوين، اوهمراه آنها به شيراز خواهد آمد. او به بازار رفت وبه دلالهاى ملك گفت كه آن كاروانسرا را برايش خريدارى كنند حتى اگرمالك تمايلى به فروش نداشته باشد. سرانجام توانست كاروانسرا راخريدارى نمايد ، سپس به كاروانسرا رفت وآن سرايدار رااخراج كرد. سرايدار مذكور چندين بار طلب بخشش كرد ولى او هرگز راضى به بخشش او نگرديد. او چند ماهى در قزوين اقامت داشت تا قافله اش از تبريز بر گردد، در اين چند ماه مدير ، سرايدار ، كارمند براى كاروانسرا استخدام نمود و نام آنجا رانيز سراى حاج چورك ناميد كه اكنون نيز آثار ان در قزوين باقى است
.
كاروانسراى حاج چورك تا سال ١٣٠٤ به صورت كاروانسرا مورد بهره بردارى قرار داشت ، در اين سال احتمالاً بدستور رضاشاه ملك مذكور مصادره گرديده ودراختيارتعداد زيادى كولى اهل تسنن كه ازمحل زندگى خودشان به قزوين تبعيد گرديده بودند قرار مى گيرد. پس از انقلاب اسلامى ملك مذكور تسطيع گرديده وهم اكنون به صورت پاركينگ مورد استفاده شهردارى قرار دارد. 
 حاج چورك دخترى از قزوين انتخاب كرده واو رابه عقد خود در آورد. براى او خانه وزندگى تهيه نمود. ازآن ببعد هميشه در قزوين اقامت بيشتر داشت و بعضى اوقات هم تا رفت وبرگشت قافله اش نزد همسر جديدش زندگى ميكرد ، از آنها پسرى متولد گرديد كه او راحاج آقا نام نهادند كه نسل ما از او ميباشد
.', NULL, 'Qazvin, Iran', '2026-08-27T08:32:46.753Z');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('66c47a4c-ae2a-413a-9b65-94960fc9b131', '5774bef5-ea8f-429e-9c05-3859bfd19982');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('66c47a4c-ae2a-413a-9b65-94960fc9b131', '621e5cc2-4033-4f42-8fa2-1c82347d7a86');
INSERT INTO stories (id, title, body, original_body, date, place, created_at) VALUES ('ea845886-abf1-4ad5-80db-5413f1802f87', 'Mohammad Zehtab (Darabi), fourth generation', 'Told by Mohammad Darabi, sixth generation.

After Haj Agha came his son Haj Khalil, and unfortunately we have no sound information about either Haj Agha or Haj Khalil. Haj Khalil''s son was named Mohammad, and he is the fourth generation of the family tree. He was born in 1235 Solar Hijri (1856) in Qazvin and died in 1318 (1939).

He was very active and industrious as a child. From early adolescence he took up the making of gut string, from sheep intestine. In those days gut string was used only in the bows of cotton-carders and, occasionally, for stringed instruments. He was forever experimenting in his cellar to better the work and raise the quality of what he made, and he repeated the experiments for several years until at last, by steeping the sheep gut in a mixture of egg and several herbal preparations, he was able to increase its durability and arrive at the string he was after.

Now he needed a market for it, and the best was the market of the cotton-carders in the town of Saveh, since Saveh produced the most and the best quilts in the country. So he gave several strings of his new product to Hossein, his eldest son, and told him to give one away free, in the Saveh bazaar, to one shop in every ten. He did so, and within a few months buyers of gut string from Saveh and several other towns were writing to them and showing great interest. He brought his new product to market and gradually came into good circumstances.

At that time — the Qajar period — Tabriz, as the seat of the crown prince, was also the country''s commercial centre, and there a great Iranian merchant named Haj Reza Toubi had begun sorting gut. He founded a large factory, installed some two hundred workers (German girls) on the premises, and asked all the gut-string makers of the country to clean the gut and make it ready in its original state for him. Mohammad Zehtab''s sons, given their family''s circumstances, set about founding a company, whose shareholders were Mohammad Zehtab and his sons Hossein, Ramazan and Ghassem, and his grandson Asadollah. With the new company and factory, Mohammad worked alongside his children with great perseverance: Hossein ran the company, Ramazan was responsible for buying and for finding markets to sell in, Ghassem was responsible for the factory, Asadollah was bookkeeper of the factory and the slaughterhouse, and Mohammad himself oversaw the workers and kept control of the stock.

Mohammad''s wife was named Salmeh and came from a good family; she was a kind woman and a devoted mother, tall, with a beautiful face. They say Salmeh Khanom had a gift for making up faces: at some celebrations and private parties she would make one half of her face very beautiful and the other half very ugly, and appear at the party like that. She died of illness in middle age. Some years later Mohammad''s children chose another wife for their father, and this second wife was at his side to the end of his life.

Mohammad Zehtab was a very good man, devout and upright. In his own lifetime he lost his eldest son, Hossein. It is said that he was still working at the factory the day before he died, though he was more than a hundred years old. At his death he had his wife call the whole family, and his children and grandchildren all came to the house. He said goodbye to them and kissed them, then lay down in a bed laid facing the qibla, took the hand of his eldest son Ramazan and asked him to look after the whole family. He told him: I have bought a grave and spoken to the mosque about the funeral; I have made ready the cost of the whole ceremony and put it on the ledge of the room; I owe nothing to anyone and no one owes anything to me, and now I wish to leave you all for good. Then he said goodbye to the family again and, smiling, closed his eyes, and having said a prayer died at once. His children, astonished at the manner of their father''s death, buried him with particular ceremony in the place he had appointed and performed the rites.

He was the pivot of the family, and the main branches of the family begin with his children.', '٢- محمد زهتاب ( دارابى) نسل چهارم
نقل از آقاى محمد دارابی نسل ششم
بعد از حاج آقا پسرش حاج خليل بود كه متاسفانه هيچگونه اطلاعات درستى از حاج اقا وحاج خليل نداريم ،فرزندحاج خليل محمد نام داشت كه او نسل چهارم شجره نامه ميباشد ، او در سال ١٢٣٥ هجرى شمسى در قزوين متولد گرديد ودر سال ١٣١٨ در گذشت. او در كودكى بسيار فعال و كوشا بود ، از ابتداى نو جوانى به ساخت زه ( از روده گوسفند) رو آورد ،در آن زمان كاربرد زه فقط در كمانهاى حلاجى واحيانا در بعضى مواقع جهت سازهاى زهى بكار مى رفت ،او همواره براى بهتر كردن كار وبالا بردن كيفيت توليداتش آزمايشهايى در زير زمين خود انجام ميداد ، چندين سال آزمايشها راتكرار كرد تا سرانجام با خواباندن تركيبى از تخم مرغ وچند داروى گياهى در محيط واطراف روده گوسفند توانست دوام آنرا افزايش داده واز آن ،زه مورد نظرش را پيدا كند
.
حالا او بدنبال بازار براى فروش محصولات خود بود،بهترين بازار نيز بازار حلاجهاى شهر ساوه بود ، زيرا ساوه بيشترين وبهترين لحاف را در كشور توليد ميكرد ،لذااو چند زه از محصولات جديد خود را به حسين پسر بزرگش داد وباو گفت در بازار ساوه از هر ده مغازه به يك مغازه يك عدد بطور مجانى بدهد. او نيز چنين كرد ،پس از چند ماه خريداران زه از ساوه وچند شهر ديگر با ايشان مكاتبه كرده وبراى خريد زه علاقه بسيارى نشان دادند. او محصول جديد خود راببازار ارائه داد. كم كم وضعيت مالى خوبى پيدا كرد، از جانب ديگر در آن زمان كه دوران حكومت قاجاريه بود ، وشهر تبريز كه شهر وليعهد نشين بشمار ميرفت مركز تجارى كشور نيز محسوب مى گرديد. در آن شهر توسط يك تاجربزرك ايرانى بنام حاج رضا توبى سرت روده آغاز شد. ايشان كارخانه بزرگى تأسيس كرد،وحدود دويست كارگر ( دختر آلمانى) در محل كارخانه مستقر نمود و از تمام زهتابهاى كشور خواسته بود كه روده را پس از پاك كردن بصورت اورژينال آماده و دراختيار او قرار دهند ، پسران محمد زهتاب نيز با توجه به وضعيت مالى خانواده خود اقدام به تأسيس شركتى نمودند كه سهامداران آن محمد زهتاب وپسرانش حسين، رمضان، قاسم ونوه اش اسدالله بودند. محمد با تأسيس شركت وكارخانه جديد با پشتكار فراوان با فرزندان خود همكارى ميكرد،بدينگونه كه حسين مديريت شركت، رمضان مسئول خريد وپيداكردن بازارهاى فروش، قاسم مسئول كارخانه ، اسدالله حسابدار كارخانه وكشتارگاه ومحمد نيز ناظر به امور كارگران وكنترل موجودى را بعهده داشت
.
همسر محمد سلمه نام داشت و ازخانواده اى خوب بود، او زنى مهربان ومادرى فداكار بشمار ميرفت، داراى قامتى كشيده وچهره اى زيبا بود، مى گويند سلمه خانم از هنر گريم وآرايش بهره مند بوده ، بطوريكه در بعضى از جشنها و ميهمانيهاى خصوصى نصف صورت خودرابسيار زيبا ونصف ديگر رابا گريم بسيار زشت مى ساخته و در ميهمانى ظاهر مى گرديده. او در ميانسالى بعلت بيمارى در گذشت. پس از چند سال فرزندان محمد براى پدرشان همسر ديگرى انتخاب نمودند ، همسر دوم تا آخرعمر محمد در كنار او بود
.
محمد زهتاب بسيار خوب ،موئمن وپاك بود ،او درزمان حيات خود پسر بزرگش حسين رااز دست مى دهد، گفته ميشود تا روز قبل از فوت خود در حاليكه سنش افزون بر صد سال بود در كارخانه كار مى كرده وهنگام مرگ تمام فاميل خود را توسط همسرش دعوت مى نمايد ،فرزندان ونوه هايش همگى بخانه اش مى روند، او با همگى خداحافظى كرده وآنها را مى بوسد ،سپس در رختخوابى كه رو بقبله انداخته بود دراز مى كشد ودست پسر بزرگش رمضان را دردست گرفته واز او مى خواهد مواظب تمام فاميل باشد. باو مىگويد يك قبر خريدارى وبا مسجد هم جهت بركذارى ختم صحبت كرده ام ،هزينه هاى كل مراسم را نيز آماده ودر طاقچه اطاق گذاشته ام به هيچ كس بدهى نداشته واز هيچ كسى هم طلبى ندارم ومى خواهم ديگر براى هميشه شماها را ترك كنم ، انگاه مجددا از فاميل خداحافظى كرده وبا لبخند،چشمهاى خود را بسته وپس از خواندن دعا بلا فاصله فوت مى نمايد. فرزندان او كه از نحوه فوت پدرشان متعجب گرديده بودند با تشريفات خاصى او رادر محل تعين شده دفن ومراسم لازم را انجام مى دهند. او محور خانواده بوده و شاخه هاى اصلى خانواده نيز از فرزندان او اغاز مى گردد
.', NULL, 'Qazvin, Iran', '2026-08-27T08:32:46.753Z');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('ea845886-abf1-4ad5-80db-5413f1802f87', 'c8a1f8a4-d83d-4638-8de4-ceb8246908cb');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('ea845886-abf1-4ad5-80db-5413f1802f87', 'a3722426-7543-4b22-a6ab-2eb3118f5d87');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('ea845886-abf1-4ad5-80db-5413f1802f87', '621e5cc2-4033-4f42-8fa2-1c82347d7a86');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('ea845886-abf1-4ad5-80db-5413f1802f87', 'aa78df60-be8d-40a8-bb52-5bd4f5a86bb6');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('ea845886-abf1-4ad5-80db-5413f1802f87', 'e2ff5ca0-38d1-4bf1-9c3f-ff60c016ecbd');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('ea845886-abf1-4ad5-80db-5413f1802f87', 'd8b95bb0-e98f-44a5-a038-3f68237f5a0e');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('ea845886-abf1-4ad5-80db-5413f1802f87', 'ba4b61e3-4b59-4d8b-8e37-5733c2951d41');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('ea845886-abf1-4ad5-80db-5413f1802f87', 'ddd5b30f-dce9-440d-bf17-b99dd3ec9a35');
INSERT INTO stories (id, title, body, original_body, date, place, created_at) VALUES ('844b9230-48fb-4d7e-88df-24f4cadcfd81', 'The main branches of the family', 'Told by Mohammad Darabi, sixth generation.

The principal branches of the family, the ones that set its main lines, are the children of Mohammad Zehtab (Darabi). Their names in order of age are Hossein, Fatemeh, Ramazan, Ghassem and Abbas. The last of them died in his youth.

A short account of each is given below.', 'سرشاخه ها
نقل از آقاى محمد دارابی نسل ششم
سر شاخه هاى فاميل كه نقش محورى را تعين مى كنند ، فرزندان محمد زهتاب (دارابى) مى باشند اسامى آنها بترتيب سن عبارتست از حسين، فاطمه، رمضان ، قاسم وعباس ، نفر آخر در نوجوانى فوت مى كند، 
اينك مختصرى از هر كدام در زير باطلاع مىرسد
.', NULL, NULL, '2026-08-27T08:32:46.753Z');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('844b9230-48fb-4d7e-88df-24f4cadcfd81', 'c8a1f8a4-d83d-4638-8de4-ceb8246908cb');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('844b9230-48fb-4d7e-88df-24f4cadcfd81', 'e2ff5ca0-38d1-4bf1-9c3f-ff60c016ecbd');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('844b9230-48fb-4d7e-88df-24f4cadcfd81', '660e6499-1a6e-4214-b532-33a428c79742');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('844b9230-48fb-4d7e-88df-24f4cadcfd81', 'd8b95bb0-e98f-44a5-a038-3f68237f5a0e');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('844b9230-48fb-4d7e-88df-24f4cadcfd81', 'ba4b61e3-4b59-4d8b-8e37-5733c2951d41');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('844b9230-48fb-4d7e-88df-24f4cadcfd81', '9b32dea9-8c7c-41a1-9aa5-552816721199');
INSERT INTO stories (id, title, body, original_body, date, place, created_at) VALUES ('aa087702-c39c-4649-a6bf-c8a726db7efc', 'Ghassem Darabi, fifth generation', 'Told by Mohammad Darabi, sixth generation.

The family''s third son was named Ghassem, and he was born in 1282 Solar Hijri (1903) in Qazvin. He too was tall and strongly built, and among his qualities were shrewdness and a cool head. From adolescence, more or less, he worked in the factory at the gut trade. He had a thorough command of it, and in his day was perhaps the leading man in the country in that work.

In 1326 (1947) he moved with his family to Tehran and took up trade there. Being inventive, capable and greatly persevering in his work, he was able to become a successful merchant. He then set about founding a factory and took up the sorting of gut, and afterwards founded a salambour works, for the processing of hides; in both of these he was very successful and became well known among his colleagues.

His wife was named Robabeh Masoudi, daughter of Haj Mirza Agha; her brothers and sisters were Ebrahim, Esmail, Mahmoud, Fatemeh and Masoumeh. In her husband''s house Robabeh was called Khanom Aziz. Of Ghassem and Robabeh six sons and two daughters remain: Kazem, Ashraf, Reza, Mohammad Taghi, Mohammad Karim, Effat, Mohammad Rahim and Nasser — and sadly Mohammad Karim, a respected and very charitable man, died in 1391 (2012).

Ghassem died of a heart attack in Farvardin 1358 (March–April 1979), at the age of seventy-five.', '٦-قاسم دارابي نسل پنجم
نقل از آقاى محمد دارابی نسل ششم
پسر سوم خانواده قاسم نام داشت كه در سال ١٢٨٢ هجرى شمسى در قزوين متولد گرديد. او نيز داراى قامتى بلند واسكلت ورزيده اى بود، هوشيارى وخونسردى از محاسن او بشمار مى رفت وتقريباً از نو جوانى در كارخانه مشغول بكار روده بوده است. در كار روده بسيار مسلط وشايد در زمان خود بالا ترين فرد در كشور محسوب مى گرديد
.
ايشان در سال ١٣٢٦ همراه خانواده اش به تهران كوچ نمود، ودر آنجا مشغول تجارت گرديد، باتوجه باينكه او فردى مبتكروتوانا وداراى پشتكار زيادى در كارخود بود، توانست به تاجرى موفق تبديل گردد. سپس او اقدام به تأسيس كارخانه نموده و به امور سرُت روده پرداخت وسپس يك كارخانه سالامبور سازى تأسيس كرد و در اين دو كار نيز بسيار موفق ودر بين همكاران خود معروف گرديد
.
همسر او ربابه مسعودى نام داشت كه دختر حاج ميرزا آقا وبرادران وخواهرانش ابراهيم، اسماعيل، محمود، فاطمه ومعصومه بوده اند، ربابه را در خانه همسرش خانم عزيز نام نهادند. از قاسم وربابه شش پسرو دودختربنامهاى كاظم، اشرف، رضا، محمدتقى، محمدكريم، عفت، محمدرحيم وناصرباقى ماندند (كه متأسفانه محمد كريم كه فردى محترم وبسيار خير بود در ١٣٩١ درگذشت). قاسم در فروردين ١٣٥٨درسن ٧٥سالگى بعلت سكته قلبى فوت مى نمايد
.', NULL, 'Tehran, Iran', '2026-08-27T08:32:46.753Z');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('aa087702-c39c-4649-a6bf-c8a726db7efc', 'ba4b61e3-4b59-4d8b-8e37-5733c2951d41');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('aa087702-c39c-4649-a6bf-c8a726db7efc', 'ff44c685-6e7b-466d-be16-212103aed41a');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('aa087702-c39c-4649-a6bf-c8a726db7efc', 'b9a60325-2ac4-4f02-ab3b-05e4a182195f');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('aa087702-c39c-4649-a6bf-c8a726db7efc', '50969cfc-76ac-45f5-815b-ba12e9db3f72');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('aa087702-c39c-4649-a6bf-c8a726db7efc', 'ffa7e4d5-1125-4053-b53d-064ff386a2a5');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('aa087702-c39c-4649-a6bf-c8a726db7efc', '8086a173-f825-4d68-8d46-48c3e9cc1acc');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('aa087702-c39c-4649-a6bf-c8a726db7efc', '1ea3983b-c3a2-49f6-979c-61edf9f1bcf8');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('aa087702-c39c-4649-a6bf-c8a726db7efc', '545b54a6-270d-4085-a95a-2bf0b24b6111');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('aa087702-c39c-4649-a6bf-c8a726db7efc', 'ac2258f8-ac57-4394-a5f4-dcedbfd7cbe0');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('aa087702-c39c-4649-a6bf-c8a726db7efc', '3c26160c-dd1f-4a52-ab2f-abf5ff0f9fbe');
INSERT OR IGNORE INTO story_people (story_id, person_id) VALUES ('aa087702-c39c-4649-a6bf-c8a726db7efc', '85f4b8fd-8b87-454b-bfb2-4da7cdbf7727');
INSERT INTO change_log (id, actor_email, kind, summary, payload_json, created_at) VALUES ('7bc9c73c-6f35-4344-b393-b23f8e079554', 'ramine@ramine.net', 'import_legacy_stories', 'Imported 6 Persian family histories from the legacy archive as stories.', '{"entries":["A historic marriage: already imported, unchanged","Hossein Zehtab (Darabi), fifth generation: already imported, unchanged","Ramazan Darabi, fifth generation: already imported, unchanged","Fatemeh Darabi, fifth generation: already imported, unchanged","Ghassem and Asadollah, the first in the family to read and write: already imported, unchanged","The two Ramazans'' journey to Qom: already imported, unchanged","A day''s hunting: already imported, unchanged","The customs duty on gut: already imported, unchanged","The dedication (2013) — 391 chars original, 618 chars English, 10 people","How this biography was written (2013) — 1049 chars original, 1374 chars English, 12 people","Haj Chorok, first generation — 2965 chars original, 3227 chars English, 2 people","Mohammad Zehtab (Darabi), fourth generation — 3481 chars original, 4081 chars English, 8 people","The main branches of the family — 270 chars original, 316 chars English, 6 people","Ghassem Darabi, fifth generation — 1110 chars original, 1345 chars English, 11 people"]}', '2026-08-27T08:32:46.753Z');
