// English translations of the archive's Persian family histories.
//
// The archive wrote these in Persian and those words stay in the record
// (`original_body`); this is the English a reader meets first (`body`), kept
// faithful to the original rather than tidied or abridged. Solar Hijri years
// are given as the archive states them, with the Gregorian year in brackets.
//
// Keyed by the story title in scripts/import_legacy_stories.mjs.
export const TRANSLATIONS = new Map([
["A historic marriage", `This was around the years 1306 to 1308 Solar Hijri (1927–1929). The partnership of Mohammad Zehtab, Hossein, Ramazan and Ghassem Darabi and Asadollah Jaberian was still going, and the running of the company had gradually passed to Ramazan Darabi.

At that time one of the merchants of Qazvin, a much respected man from a good family, ran into financial trouble. He sold most of what he owned and cleared his debts, but he had no capital left to carry on with. Ramazan Darabi, hearing of his situation, invited him to come and work in their company, and he accepted, joining them as mirza — the bookkeeper. Ramazan had also said to him that, God willing, when the time came to find a wife for Ghassem, they would ask for his daughter. The man was very glad of that promise.

In those days Hossein Darabi was locked in a bitter quarrel with Haj Mirza Agha Masoudi, the head of the butchers' guild, and it had dragged on a long time. Ramazan and Ghassem were tired of the feud and wanted an end to it. One day a man came to Ramazan and said: how long are these two families going to fight? Both are good families, both are sensible people — why not make peace and be friends? Ramazan said, I am tired of it myself, but our brother will not give way. The man said, you could begin by asking for Haj Mirza Agha's daughter for Ghassem. Ramazan said, does Haj Mirza Agha have a daughter? He said, yes — several.

Ramazan went straight to his own wife, to Hossein's wife and to his sister Fatemeh and told them: buy sweets at once, go to Haj Mirza Agha's house, make peace, and while you are there ask for his daughter for Ghassem. They bought a sugar cone and sweets and went. Haj Mirza Agha's family received them warmly, and answered the proposal yes. So two families who had been at odds for years came into good relations again over this marriage.

Ramazan Darabi set the date and bought the invitation cards. He had forgotten the promise he had made earlier to his bookkeeper about the man's daughter. He put the cards down on the mirza's desk. When the former merchant saw them he asked what they were. Ramazan said, we have taken Haj Mirza Agha's daughter for Ghassem. The man went faint and collapsed to the floor. Several people lifted him up, and when he had come round Ramazan asked what had happened. Still stricken, he said: but you promised you would take my daughter for Ghassem.

Ramazan was deeply upset at what had happened and furious with himself for having broken the old man's heart. After a few minutes' thought he said: do not be distressed — I will take your daughter for Asadollah, my sister's son. There is no difference between them. The man was overjoyed and told his family at once. Asadollah Jaberian, working in the factory, was hardly more than a boy at the time; when he came home from work they told him his wedding would be in two nights. Stunned, he told his mother and father, and they agreed. And so in one night two marriages were held, Ghassem Darabi's and Asadollah Jaberian's.

Ramazan Darabi was very fond of both bridegrooms — his brother and his nephew — and wanted to throw a great celebration. But a senior cleric named Haji Mojtahed (Shahidi) lived next door, a man who visited the family and was on good terms with them, and who held the sound of music to be forbidden. Out of respect Ramazan hired only a few players of violin and tar, and told them to play softly.

The wedding began and the guests were received in the courtyard. Suddenly one of the servants came to Ramazan and said Haji Mojtahed was out in the lane making a scene. Ramazan went out and found the cleric pacing furiously and cursing them, with a crowd of neighbours who had not been invited standing round watching. He greeted him respectfully and asked what the matter was. The cleric swore at him again and said: you have brought musicians? Ramazan said yes, but I told them to play quietly so as not to disturb you. The cleric said, throw them out this minute. Ramazan said, Haj Agha, we have many guests, it would not do to throw them out now — please let it go and let these people go home.

The cleric let out another string of obscenities, and at that Ramazan lost his temper and said: Haj Agha, a man's four walls are his own business — what has it to do with you? If you are so honest, go and stop your own brothers from visiting houses of ill repute. The cleric said, you are lying. Ramazan said, they are there right now. He said, then prove it — and told his servant, Darvish, go with Ramazan this instant, and if he cannot prove it I will break up this wedding tonight.

Ramazan and Darvish took the cleric's own carriage to the disreputable quarter of Qazvin and stopped in front of one of the houses. Ramazan said, Darvish, are you coming in with me? Darvish said no, you go in. Ramazan went in and, in an upstairs room with a window onto the lane, found the cleric's brothers sitting with the women of the house and drinking. He greeted them and said, I invited you to the wedding — why did you not come? They said, Haj Agha is there, we cannot come. Ramazan said, why have you left your turbans lying beside the drink? At least keep some respect for them. He gathered the turbans up, wrapped them in a large silk cloth and set the bundle on the ledge; then he sat a few minutes, drank a glass with them, said goodbye, and on his way out quietly took the bundle of turbans down with him.

Darvish, who had heard the brothers' voices through the window and now saw their turbans, said: do not take them. Ramazan said, it is not only Haj Agha who needs to know — the people of the quarter should know too, and Haj Agha should be ashamed and stop troubling his neighbours.

They came back to the cleric's house, where he was still pacing the lane and cursing. He asked Darvish whether it had been proved that Ramazan was lying. Ramazan answered: here are their turbans — and Darvish confirmed it. The cleric went into his house at once out of shame.

Ramazan told one of his friends to carry the turbans back and put them on the ledge of that room without the men noticing. Then he sent someone for army buglers, invited several of them, invited every onlooker in the lane to the wedding as well, and told them all: they will play loud until morning, and you will celebrate. That night was one the neighbourhood never forgot, and from then on Haji Mojtahed went home quietly and troubled his neighbours no more.`],

["Hossein Zehtab (Darabi), fifth generation", `Hossein Zehtab was born around 1261 Solar Hijri (1882) in Qazvin. He was a small man, very quick and capable, and also kind, devoted to his family and to people.

In those days the boys of a neighbourhood were forever in scraps with one another, and those among them with a gift for leading were chosen to lead the group. He was one of these, always the leader and the first among his friends; in a fight he could face a good number of young men on his own and beat them all. He was hospitable, and everyone knew him as a generous, open-handed man.

By his wife Ategheh Khanom he had three children: Gholamreza, Gholamhossein and Akram. Gholamreza died of illness in childhood, and his birth certificate was given over to Gholamhossein, who from then on was known as Gholamreza.

At one point he travelled to Iraq with a party from Qazvin to make the pilgrimage to Karbala. Travel then was by litter, cart or horse, so the journey took three or four months. Plague was going about in Iran at the time, and Iraq put the travellers under a month's quarantine, shut up in a caravanserai. Hossein, impatient to reach Karbala, could not bear it. Noticing one day that the outer wall of the fort was not quite vertical but sloped, he decided to get away over it: he took up a brick in both hands, set its other side against the wall, and — hoping to slide down it — threw himself over in full view of his fellow travellers. He fell fifteen metres to the ground and lost consciousness. The travellers who saw it all thought he had died. The Iraqi officers put him on a board and carried him off.

A few days later the travellers were released and went on to Karbala. Three months after that the same party returned and were met by the people of Takestan, and Hossein's family had gathered there to welcome him — but they did not see him, and heard from the travellers that he had died. They held a funeral for him and the whole family went into mourning.

Four months later a man came from Takestan and told Hossein's brothers that Hossein Zehtab was waiting for them in Takestan. They did not believe it and said, Hossein is dead. The man gave them a bamboo cane and said, Hossein gave me this. Since a bamboo cane was a mark particular to the Zehtabs, they believed him and hurried to Takestan, where they found Hossein alive. He told them he had lain three months in a hospital in Baghdad until all his broken bones had healed, and had had no way of getting word to them. They were overjoyed and held a great celebration.

Ategheh Khanom, Hossein's wife, was a good woman, devout and very kind, and from a good family. As the custom then was for the bridegroom's family to change a bride's name when she came into their house, in her husband's home she was called Gelin Khanom.

Hossein died of illness in 1316 (1937), at the age of fifty-five, while his father was still living.

It is worth noting that for a time he was bitterly at odds with Mehdi Zehtab, and in the end took his daughter for his brother Ramazan; and for a time he was at odds with Haj Mirza Agha Masoudi, whose daughter in the end became the wife of his other brother, Ghassem.`],

["Ramazan Darabi, fifth generation", `Ramazan Darabi was born in 1272 Solar Hijri (1893) in Qazvin. Like his sister Fatemeh Khanom he was tall and strongly built, and among his qualities were a sharp intelligence and a gift for speaking.

At fifteen he went as apprentice to a great Armenian merchant named Mikael Khan, worked there several years and learned the secrets of the trade. Then at eighteen he entered the service of Mehdi Zehtab as an adviser, worked with him for some years too, and learned the gut and hide trade from him. After that he joined his father and brothers, and as he had a great deal of experience in trade and dealing, he took charge of buying and selling in the partnership.

While he was with Mehdi Zehtab he had lost his heart to his daughter Farrokhandeh, but as his elder brother Hossein was bitterly at odds with Mehdi Zehtab he never raised it. Meanwhile his father and brother were forever trying to choose a wife for him and he would not have it, until one day Hossein, Hossein's wife and his father's wife cornered him and pressed him on why he would not marry. Under that pressure he said he wanted Farrokhandeh. Hossein immediately told his wife and his mother: go to Mehdi's house at once, make peace, and then ask for Farrokhandeh for Ramazan. They went, won the family over, and in the end the marriage took place.

Farrokhandeh was a hardy, strong woman, and kind as well; in her husband's house they called her Aziz Khanom. They lived together some fifty-eight years and had nineteen children, of whom seven died in childhood of illness. Six sons and six daughters remain and are living: Aghdas, Akhtar, Farangis, Mehrangiz, Mohammad, Mehdi, Bagher, Asghar, Mahin, Manijeh, Ali and Hojjat.

Ramazan died of cancer in 1365 Solar Hijri (1986), at the age of ninety-three. It is worth noting that he was born in the month of Ramadan and died in the month of Ramadan.`],

["Fatemeh Darabi, fifth generation", `Fatemeh Khanom was born around 1268 Solar Hijri (1889) in Qazvin. She was composed, dignified and beautiful, and tall as well. Good housekeeping, raising her children well and devotion to the family were counted among her qualities.

Her husband, Haj Ramazan Jaberian, was a devout man, chaste, quiet and retiring; he worked in the Qazvin bazaar selling produce and goods on commission.

Like her mother Salmeh, Fatemeh Khanom had four sons and one daughter: Asadollah, Seifollah, Farajollah, Ezatollah and Kobra. In her husband's house they called her Mirza Baji.

Fatemeh Khanom died in middle age, leaving a very great grief in the hearts of her children, her brothers and her husband.

(Anyone of the respected Jaberian family, or anyone else who knows more about Fatemeh Khanom, is asked to send that information to me, Mohammad Darabi, or to Dr Nasser Darabiha, so that it can be recorded in their name. Thank you.)`],

["Ghassem and Asadollah, the first in the family to read and write", `The partnership of Mohammad Zehtab, his sons and his grandson gradually prospered. Ramazan Darabi, who through constant travelling and dealing with many merchants had gained standing and a greater command of speech, arranged to send gut to a new merchant in Tabriz who, alongside Haj Reza Touba, was in the gut trade. The merchant was German and went by the name Monsieur Kass; he had a large trading house, a factory and a great many staff. As the gut that went from Qazvin was very good, he telegraphed their company from Tabriz and asked them to send a representative to sign a contract. Ramazan Darabi was appointed by the company for the task and sent to Tabriz.

In those days most people in the country — and the Darabi brothers and Asadollah Jaberian among them — were illiterate, for want of schools, for want of any habit of schooling in the family, and because there was so much work; they even used a seal or a fingerprint to sign with. Ramazan Darabi was illiterate too, but because he presented a case well and understood the social dealings of the day, he was chosen to sign the contract and set off for Tabriz.

He went to the address he had been given and asked the gatekeeper for Monsieur Kass. The gatekeeper told him to go into the building and along to room number seven. He went in — and having no letters, did not know which was number seven. There was no one in the corridor to ask. He was ashamed of not being able to read, and understood then that reading is a very good thing. There was nothing to be done. All he knew was that the figure one is long, like a goat's horn. He saw that the first door on the left had a long figure above it, and said to himself: this must be one, and the one opposite must be two, and that one three — and so he found number seven.

He went in, introduced himself to the secretary, was presented to Monsieur Kass, and talked with him, his interpreter and his legal adviser for about three hours. Then the four of them went to the notary's office, where he haggled with Monsieur Kass and his lawyer for about two hours more in front of the notary, checking every clause of the contract by having the lawyer read it aloud. The contract was entered in the register, and when it came to signing, Ramazan Darabi got out his seal to press beneath it.

At that the notary grew annoyed and burst out: sir, why do you not sign? Ramazan Darabi said, I have no letters, I do not know how to sign. At this announcement Monsieur Kass, his lawyer and the notary were astonished, and began to think something of him that was far from the truth. The notary cried out again: I do not believe it.

Ramazan Darabi, who the day before his journey to Tabriz had concluded another contract in Qazvin and still had it in his pocket, took it out and said to the notary: look, I sealed this one too. The notary, who had been eyeing him sideways, saw the contract, sprang up, took him in his arms, kissed his face several times and said: this, too, shows how clever you are, and I thought wrongly of you — forgive me. With the objections you raised against Monsieur Kass's lawyer for two hours, and the way you turned the contract to your own advantage, I thought you had a very high legal education. When you said you could not read I did not believe it at all; if you had sworn to it I still would not have believed it. Only on seeing this contract, drawn up in a Qazvin notary's office and bearing the signature of Haj Mirza Ishaq, whom I hold in great respect, could I believe that you truly cannot read — and I am truly astonished. Then he kissed him again and said: my son, why can you not read? You could go to school this very moment. It is a real pity.

After the contract was signed, on the journey home, Ramazan — who suffered from being unlettered — sat on the bus turning the notary's words over, and sank into thought. He said to himself: my own work is heavy, but I had better think of the children. When he reached Qazvin, at the first opportunity he took Ghassem and Asadollah to night school and encouraged them to study. They were past school age and under the weight of a day's work, but they went to class in the evenings until they could read and write reasonably well.

After them came Seifollah and Farajollah Jaberian, Gholamreza and Aghdas Darabi, and in turn all the children went to school at the proper age and learned to read. And it is a matter of pride today that the family counts a great many professors, doctors, engineers, holders of master's degrees and the like.`],

["The two Ramazans' journey to Qom", `There is information about the principal branches of the family and their relatives, which I write down here for the dear family.

One day Ramazan Jaberian meant to travel to Qom to visit the shrine of Hazrat-e Masumeh. Ramazan Darabi was twelve at the time and eager for the pilgrimage too, so he asked his father and mother to let him go with Ramazan Jaberian, his sister's husband. They agreed, and asked Mr Ramazan Jaberian to take good care of little Ramazan.

Having accepted the charge, Ramazan Jaberian bought a donkey to carry his loads, put his travelling baggage on it, took his brother-in-law by the hand, and after their goodbyes they set out. They were two nights on the road, little Ramazan riding the donkey at times and walking at others, until at dusk on the third day they came into Qom and went straight to the shrine of Hazrat-e Masumeh.

There, after their ablutions and their visit, they took their places for the congregational prayer. Little Ramazan, with three days of the road in his body, was at the very end of one of the rows; in prostration he fell asleep on the prayer-stone, and a curtain that hung beside him came down over him, so that without knowing it he was hidden behind it.

After the prayer Ramazan Jaberian could not see him and went looking. He was beside himself at having lost the boy and did not know what he would say to his parents. He searched the whole shrine courtyard, the streets and the lanes around it, and at last went to the police station and reported little Ramazan missing. He could not sleep all night.

The next morning he went to the shrine again for the congregational prayer and began to pray. Little Ramazan, still asleep behind the curtain, woke during the dawn prayer and thought he was in the middle of the night prayer. When it ended he found Ramazan Jaberian and went to him. Ramazan Jaberian, seeing him, was overjoyed and asked: where were you since last night? Puzzled by the question, the boy said: why since last night? We arrived tonight, we prayed, and now the prayer is over. When Ramazan Jaberian looked at the place where he had slept he understood that the boy had been hidden behind the curtain and had slept there till morning, and he treated him with delight.

After a few days of visiting and going about, they returned to Qazvin.`],

["A day's hunting", `One Friday in winter in the city of Qazvin, Hossein Zehtab (Darabi) and two of his friends, together with Ramazan Darabi, who was about thirteen, went up into the mountains north of Qazvin to hunt partridge. There was about twenty centimetres of snow on the ground, but the weather was sunny and fine and they were enjoying the walk over the snow.

Suddenly they saw a boy running towards the city in tears. Hossein said to him, what has happened, where are you going? The boy said, my brother has fallen into a well. Hossein and his companions ran at once to the well he pointed out and saw that the stones around it had fallen in. The boy said, my brother is under those stones. With great difficulty they lifted the stones away and pulled out the boy's brother, who was still alive. After they had given him some food and fruit they asked why he had gone down the well. He said: I have no work and no income; I went down to catch a rock dove to eat, and the stones came down on me. The hunting party gave the boy and his brother some money and went on their way.

Half an hour later they saw an old man sitting near a hut, weeping. They asked what had happened. He said: I have nowhere to live and I live in this hut, and I always take my water from this well; today the bucket I draw water with fell into the well and I do not know how to get it out. Hossein asked one of his companions, can you go down the well? He said yes, went down, and after a while brought the bucket up. The old man was delighted, Hossein gave him some money as well, and the hunting party set off again into the open country.

It was nearly noon when they suddenly heard the sound of a fight from inside a small room out in the country. They went closer and saw a boy bound hand and foot in the middle of the room, and four men fighting one another. They meant to assault the boy and each wanted to be first, and they had even drawn knives on each other. Hossein Zehtab rushed into the room and, striking their hands with his stick, knocked the knives to the ground; the men fled. Hossein untied the young man and asked why he had come with them. He said: one of them is a friend of mine, he tricked me and brought me here — it is a good thing you saved me. The young man went along with the hunting party, stayed with them until near dusk, and returned to the city with them at the end.

About twelve years later, Hossein Zehtab went to the town of Saveh to sell gut string and there fell in with a well-known man named Sadegh Savei and entered into a deal with him, in the course of which the man made off with a hundred tomans of Hossein's money and would not give it back. Hossein had no document with which to recover it and had to return to Qazvin.

Ramazan Darabi, grown up by then and a sharp-minded young man, heard the story and said: I will go to Saveh and bring that hundred tomans back to life. He laid a plan. First he went to Mikael Khan the Armenian, one of the country's well-known merchants, who lived in Qazvin and whom he had once worked for. Mikael Khan, who knew him for his good name and honesty, welcomed him and was glad to help. Ramazan said to him: in the next few days I will draw a bill on you from Saveh and send it through the Bank Melli. If I set my seal beneath the bill horizontally, agree to pay it; if I set it vertically, dishonour it and send it back. Mikael Khan agreed.

Ramazan Darabi went to Saveh, found Sadegh Savei, and entered into a deal there under the name Darabi. Sadegh Savei, who knew the family by the name Zehtab, did not realise this was Hossein's brother. He did business, bought a great many carpets, and issued the bill with the seal set vertically. The bill was presented to Mikael Khan in Qazvin, who dishonoured it and sent it back. Sadegh Savei, greatly put out, complained of Ramazan Darabi to the courthouse in Saveh, and a summons was delivered to Ramazan Darabi at his lodging house.

Ramazan Darabi went to the courthouse early, before the hour he had been called for, hoping to find some way through. In the corridor a man came face to face with him, and both felt that they knew each other. The man said: excuse me, sir, are you from Qazvin? Ramazan said yes. The man said: are you Hossein Zehtab's brother? Ramazan said, yes, I am the brother of Hossein Darabi — and you? He said: I am the very one who twelve years ago was saved by Hossein from those four men, and I am now the head of this courthouse. What are you doing here?

Ramazan Darabi told him the whole story. The man wrote a letter on courthouse paper, as though from the central courthouse to the courthouse of Saveh, put it in an envelope and gave it to Ramazan Darabi, saying: hand me this letter in front of Sadegh Savei.

At the appointed hour the court convened. Sadegh Savei, who on the strength of his friendship with the head of the courthouse had asked him to conduct the hearing himself, sat down beside the presiding chair. The president asked Ramazan Darabi: did you take this gentleman's money and defraud him? Ramazan said, yes, but I have a reason — and handed him the letter. As he read it the president held it so that Sadegh could read it too. Ramazan suddenly saw Sadegh's face change colour, for the letter said: Sadegh Savei is a swindler, send him to Tehran at once under guard.

The president said quietly to Sadegh: did you take this gentleman's brother's money? If you did, say so, and I will intercede and keep them from taking you to Tehran. Sadegh said, do something yourself. The president said to Ramazan: if he gives you your hundred tomans and the interest on it, will you withdraw your complaint? Ramazan said yes. Then the president deducted Sadegh's debt from Ramazan's, and asked Ramazan: how will you pay the rest? Ramazan said, by a Bank Melli bill to Qazvin. The court ended, Ramazan issued the bill — this time sealed horizontally — and sent it; in Qazvin Mikael Khan accepted it, and Ramazan Darabi returned to Qazvin with the goods he had bought.

This was the fruit of Hossein's good deed in saving that young man.`],

["The customs duty on gut", `After the Second World War the trading markets in Iran gradually revived. The partnership of Mohammad Zehtab and his sons was going well and they were making a success of the gut trade.

One day Mr Esmail Masoudi — the brother of Ghassem Darabi's wife — came to Ramazan Darabi with a scrap of newspaper in his hand, which he had been given at the greengrocer's when he bought vegetables, and said: they have set a customs duty on gut. As he read the waste paper out in front of Ramazan, it became clear that a notice had been printed in the paper three months earlier setting a date for the duty on gut — and that only two days of it remained. From that date on, any gut on which the duty had not been paid would count as contraband. As nobody in the family read newspapers, they had known nothing about it.

Ramazan Darabi thanked Mr Masoudi and then sank into thought, looking for a way out. He studied it and thought it over for some hours, and at last found one. He took a great quantity of the waste from cattle and sheep carcasses that was lying at the slaughterhouse waiting to be thrown away, put it into a large number of barrels, went to the customs office and submitted a request to have gut sealed. A representative came from the customs to their factory and, not knowing gut, sealed that waste in its place.

From the appointed date on, the price of unsealed gut suddenly fell by about seventy per cent and the value of sealed gut rose. They began buying unsealed gut, which was very cheap. On the day they had bought a great quantity and wanted to send it to Tabriz, Ramazan Darabi went to the representative who had come from the customs and sealed the barrels and told him: unfortunately, that day the workers had put rubbish into the barrels instead of gut by mistake, and you sealed it — please come to the factory and see. The man came, opened one of the seals, saw that it was so, and in the end put the whole of the gut in place of the rubbish and sealed it again under that day's date — receiving a fee and a bonus for it.

In this deal the company bought gut at seventy per cent below price and sold it at full price, and made a good profit.

Ramazan Darabi always told his children and those around him: whatever newspaper or writing or piece of text you see — even if it is lying on the ground — pick it up and read it.`],
]);
